apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nwhcatg1g-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap-test-organization-jk/rhtap-qe:4d9f474c0f0e93a7b3abd670db5368ca4c5525e9@sha256:ef71dd5d5ab2369e1539b8b2b43535a1a3adb32c2df0e7c5c4da88745a8534bd
          name: container-image
